project:
  type: website
  # pre-render: setup.R
  render:
    - "*.qmd"
    - "!Aim1_part1.qmd"
  output-dir: docs

website:
  title: "zfBrainAsymmetry"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - session.qmd
      - text: "Aims"
        menu:
          - Aim1_part1.qmd
          - Aim2.qmd
  page-navigation: true
  page-footer: "Copyright 2024, Vanessa Chong-Morrison" 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

bibliography: grateful-refs.bib