project:
  type: website
  pre-render: setup.R
  output-dir: docs

website:
  title: "zfBrainAsymmetry"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - session.qmd
      - text: "Aims"
        menu:
          - Aim1.qmd
          - Aim2.qmd 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

