project:
  type: website
  # pre-render: setup.R
  output-dir: docs

website:
  title: "zfBrainAsymmetry"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - session.qmd
      - text: "Aims"
        menu:
          - Aim1_part1.qmd
          - Aim1_part2.qmd
          - Aim2.qmd
  page-navigation: true
  page-footer: "Copyright 2024, Vanessa Chong-Morrison" 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    number-sections: true
    comments:
      utterances:
        repo: zfBrainAsymmetry/comments

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: auto

editor: visual

bibliography: grateful-refs.bib